--disable all

# format options

--allman false
--binarygrouping 4,8
--closingparen balanced
--closurevoid remove
--commas inline
--comments indent
--decimalgrouping 3,3
--elseposition same-line
--exponentcase lowercase
--exponentgrouping disabled
--extensionacl on-extension
--fractiongrouping disabled
--funcattributes prev-line
--hexgrouping 4,8
--hexliteralcase uppercase
--ifdef no-indent
--indent 4
--indentcase false
--importgrouping alpha
--linebreaks lf
--maxwidth 200
--octalgrouping 4,8
--operatorfunc spaced
--patternlet hoist
--ranges no-space
--redundanttype infer-locals-only
--self init-only
--semicolons inline
--stripunusedargs always
--trimwhitespace always
--typeattributes prev-line
--varattributes prev-line
--voidtype void
--wraparguments before-first
--wrapcollections before-first
--wrapconditions after-first
--wrapparameters before-first

# op-ins (enable)

--enable blankLinesAtEndOfScope
--enable blankLinesAtStartOfScope
--enable blankLinesBetweenScopes
--enable consecutiveBlankLines
--enable consecutiveSpaces
--enable duplicateImports
--enable redundantReturn
--enable semicolons
--enable isEmpty 
--enable andOperator
--enable emptyBraces
--enable enumNamespaces
--enable extensionAccessControl
--enable spaceAroundBraces
--enable spaceAroundBrackets
--enable anyObjectProtocol
--enable conditionalAssignment
--enable trailingClosures
--enable trailingCommas
--enable trailingSpace
--enable void
--enable yodaConditions
--enable indent
--enable initCoderUnavailable
--enable leadingDelimiters
--enable linebreakAtEndOfFile
--enable linebreaks
--enable redundantVoidReturnType
--enable strongOutlets
--enable strongifiedSelf
--enable todos
--enable spaceInsideParens
--enable spaceAroundComments
--enable spaceAroundGenerics
--enable spaceAroundOperators
--enable spaceAroundParens
--enable spaceInsideBraces
--enable spaceInsideBrackets
--enable spaceInsideComments
--enable spaceInsideGenerics
--enable opaqueGenericParameters
--enable fileHeader
--enable genericExtensions
--enable hoistAwait
--enable hoistTry
--enable modifierOrder
--enable redundantParens
--enable redundantPattern
--enable redundantRawValues
--enable redundantInit
--enable redundantLet
--enable redundantOptionalBinding
--enable redundantSelf
--enable redundantNilInit
--enable redundantObjc
--enable redundantExtensionACL
--enable redundantLetError
--enable preferKeyPath
--enable redundantBackticks
--enable redundantBreak

##################

#--enable hoistPatternLet
#--enable redundantGet
#--enable redundantType
#--enable assertionFailures
#--enable elseOnSameLine
#--enable redundantClosure
#--enable redundantFileprivate
--enable wrap
#--enable wrapAttributes
#--enable wrapSingleLineComments
#--enable numberFormatting
#--enable blankLinesAroundMark
#--enable wrapArguments
#--enable sortedSwitchCases
#--enable braces
#--enable sortDeclarations
#--enable sortedImports
#--enable wrapMultilineStatementBraces
#--enable typeSugar
#--enable unusedArguments
