name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        env:
          scheme: "SmartApp DEV"
        run: |
          xcodebuild build -project SmartApp/SmartApp.xcodeproj -scheme "SmartApp Dev" CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO


    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        env:
          scheme: "SmartApp DEV"
        run: |
          xcodebuild clean test -project SmartApp/SmartApp.xcodeproj -scheme "SmartApp Dev" -destination 'platform=iOS Simulator,name=iPhone 14' CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO

